### ISSUE TITLE
How to make my repo private

### ISSUE THREAD

**Issue by thomasly** [XieResearchGroup/Github-Org-Page#1]
Tried to make my repo (profoldassess) private, but it says this group need to be upgraded first. Now I can create private repos in my personal GitHub account thanks to the new GitHub policy. However, I have to make the repo public before transferring it to this group. How do I keep it private? Can anybody help?

**Comment by thomasly** [comment]
>           Just pay for the upgrade, you can try now 😃

Is this a joke?

**Comment by he-org** [comment]
no, I just paid for the upgrade, we can now use private organization repos officially.

**Comment by thomasly** [comment]
And I've made my repo private. Thanks!
