### ISSUE TITLE
Data transfer

### ISSUE THREAD

**Issue by thomasly** [XieResearchGroup/Github-Org-Page#2]
How do I download or upload files between the dgx and my local computer without using TeamViewer? I used to use scp. But our dgx station is behind two proxy to which I don't have permission to add my ssh keys. What is the correct way to create an ssh port forwarding between the dgx and my local computer? Or are there better ways to have the job done? Thank you!

**Comment by hansaimlim** [comment]
You need to connect through a machine in Hunter network.
I will set up an account in one of the Ubuntu machine in the lab.
What's your account username in DGX (or venus/saturn)?

Once set up, you can use the ubuntu machine as the middle-proxy to connect to DGX.
The process is the same as you know.
Local machine -> Ubuntu proxy machine -> DGX

What I usually do is the same, with another proxy machine in the lab.

**Comment by thomasly** [comment]
Hi Hansaim,

Thank you so much for the help. My username in DGX is yangliu.

Best,
Yang

**Comment by hansaimlim** [comment]
Created the account. I will let you know the credentials separately.
